### DISCUSSION TITLE
Nonlocal model and simulation examples

### DISCUSSION THREAD

**Discussion by 123fgh123** [damask-multiphysics/DAMASK#4] [Q&A] [answered]
Dear colleagues,

I am interested in the nonlocal model of DAMASK, and I want to know is there simulation examples (inputs) on this topic, which could be run directly?

Thanks in advance.

**Comment by 123fgh123** [comment]
I have run a simulation as attached files show, and I did not know whether the nonlocal model has worked.
[grid-nolocal.zip](https://github.com/eisenforschung/DAMASK/files/12909042/grid-nolocal.zip)

**Reply by sharanroongta** [reply]
Hi, which alpha version of DAMASK are you using?

**Reply by 123fgh123** [reply]
v3.0.0-alpha7

**Reply by 123fgh123** [reply]
The simulation log file has been attached as follow.
[grid-nolocal.zip](https://github.com/eisenforschung/DAMASK/files/13166217/grid-nolocal.zip)

**Reply by sharanroongta** [reply, marked as answer]
So, there are a few things to keep in mind. I myself am not an expert on the non-local model and have never used it. It is a difficult model to use in terms of convergence and finding the right parameter set.

- The parameters you have used follows the thesis of Christoph Kords [http://publications.rwth-aachen.de/record/229993/files/4862.pdf]. This is fine, and I would suggest you to go through his work to understand the model better
- There is one change i have made in your material.yaml, i.e., location of plastic model output. With this correction you can visualize the different dislocation densities.
```yaml
phase:
  Aluminum:
    lattice: cF
    mechanical:
      output: [F, P, F_e, F_p, L_p, O]
      elastic: {type: Hooke, C_11: 106.75e+9, C_12: 60.41e+9, C_44: 28.34e+9}
      plastic:
        type: nonlocal    
        N_sl: [12]
        output: [rho_u_ed_pos, rho_b_ed_pos, rho_u_ed_neg, rho_b_ed_neg, rho_u_sc_pos, rho_b_sc_pos, rho_u_sc_neg, rho_b_sc_neg, rho_d_ed, rho_d_sc]
        b_sl: [2.86e-10]
        V_at: 0.017e-27 # Omega
        d_ed: [1.6e-9]
        d_sc: [10.e-9]
        i_sl: [60]      # k_2 (lambda_0 in Tab. 7.1)
        f_ed_mult: 0.1  # k_1

        rho_u_ed_neg_0: [1.25e9] # 6e10 / (12*4)
        rho_u_ed_pos_0: [1.25e9] # 6e10 / (12*4)
        rho_u_sc_neg_0: [1.25e9] # 6e10 / (12*4)
        rho_u_sc_pos_0: [1.25e9] # 6e10 / (12*4)
        rho_d_ed_0: [0]
        rho_d_sc_0: [0]

        D_0: 7.e-29
        Q_cl: 0.0 # no temperature dependency
        Q_sol: 2.00272e-19 # 1.25 eV
        c_sol: 1.5e-6       # correct unit?
        f_sol: 2.0          # d_obst in multiples of b
        tau_Peierls_ed: [.1e6]
        tau_Peierls_sc: [.1e6]
        w: 10              # w_k in multiple of b

        p_sl: 1
        q_sl: 1

        nu_a: 50.e+9
        B: 1.e-2
        f_ed: 1.0  # k_3

        h_sl-sl: [0, 0, 0.625, 0.07, 0.137, 0.137, 0.122] # Table 3.4

        chi_GB: 0.5      # full blocking at GB
        chi_surface: 1.0 # no blocking at surface

        f_F: 0.0         # no line tension correction
        sigma_rho_u: 0   # no random distribution


        short_range_stress_correction: false
        rho_significant: 1.e6        
  ```
  
  You can play around with the chi_GB to see how the dislocation distribution looks like.
  
- Remember that the model is size dependent, unlike other local plastic models. Therefore RVE size is important. One can vary the size to the see the effect, like the Hall Petch effect
- To understand if the model is working or not, you can make the model behave in a `local` way, by adding this key in your plastic dictionary of the material.yaml,
```yaml
plastic:
  flux: false
  ```
  This should render 0 blocked dislocation density, and could be a check if the model is atleast working correctly or not.
  
  I hope this answers some of your questions. I would also suggest to start with a bicrystal (as used by Christoph in one of the examples in the thesis), and try to recreate that.
