### DISCUSSION TITLE
Can DAMASK Simulate Texture Evolution Under Stress

### DISCUSSION THREAD

**Discussion by CGH20171006** [damask-multiphysics/DAMASK#44] [Q&A]
Hello, everyone!

I’ve been working with DAMASK and trying to simulate the behavior of polycrystalline materials under tensile stress. I’ve run a few basic cases, but I am unable to see any grain orientation-related information in the hdf5 results. Specifically, I want to track the evolution of the grain texture during deformation.

So I think that DAMASK might not account for grain orientation transitions in its default model.

Is this correct? or do I need to add something to the model or define additional parameters to track the texture evolution? Any guidance would be greatly appreciated!

**Comment by eisenlohr** [comment]
The relevant output quantity you need to include in the HDF5 file is called "O", which is the lattice orientation in quaternion representation. Please add to your material.yaml file in the `phase: NameOfPhase: mechanical: output` list an entry for `O`.

**Reply by CGH20171006** [reply]
> The relevant output quantity you need to include in the HDF5 file is called "O", which is the lattice orientation in quaternion representation. Please add to your material.yaml file in the `phase: NameOfPhase: mechanical: output` list an entry for `O`.

OK, with your answer, I have solved this problem. But I didn't get a significant crystal rotation phenomena when I ran the DAMASK code. I guess the low strain in my code causes this. However, the damask will post this error when I try to get more strain.

```
 Piola--Kirchhoff stress       / MPa =
        0.3356       -45.9545      -234.4250
      -47.2996         0.3001      -165.9533
     -622.0288      -424.0315    177533.0421

 ... doing gamma convolution ...............................................

 ... reporting .............................................................

 error divergence =         0.96 (8.49E+07 / m, tol =  8.88E+07)
 error stress BC  =         0.00 (3.36E+05 Pa,  tol =  1.78E+08)

 ===========================================================================

 increment 67513 converged

 ###########################################################################
 Time  6.75140E+02s: Increment 67514/100000-1/1 of load case 1/1
 Increment 67514/100000-1/1 @ Iteration 1≤0≤100

 deformation gradient aim       =
   0.6279416    0.0000000    0.0000000
   0.0000000    0.6586008    0.0000000
   0.0000000    0.0000000    1.6751400

 ... evaluating constitutive response ......................................

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        error 402                                    │
 ├─────────────────────────────────────────────────────────────────────┤
 │ invalid orientation specified                                       │
 │ fromMatrix                                                          │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘

 DAMASK terminated on:
 Date:               03/12/2024
 Time:               04:29:51
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL IEEE_INEXACT_FLAG
STOP 1
```

Load.yaml is here:

```
solver: {mechanical: spectral_basic}

loadstep:
  - boundary_conditions:
      mechanical:
        dot_F:
          - [x,   0.0,  0.0]
          - [0.0,   x,  0.0]
          - [0.0,   0.0,  0.001]
        P:
          - [0.0,   x,  x]
          - [x,   0.0,  x]
          - [x,   x,  x]
    discretization: {t: 1000.0, N: 100000}
    f_out: 1000
```

material.yaml is here:

```
homogenization:
  direct:
    N_constituents: 1
    mechanical: {type: pass}
phase:
  '1':
    lattice: hP
    c/a: 1.587
    mechanical:
      output: [F, P, F_e, F_p, L_p, O]
      elastic: {C_11: 162400000000.0, C_33: 180700000000.0, C_44: 49700000000.0, C_12: 92000000000.0, C_13: 69000000000.0, type: Hooke}
      type: phenopowerlaw
      references: ['C. Zambaldi et al., Journal of Materials Research 27(1):356-367, 2021, https://doi.org/10.1557/jmr.2011.334', 'L. Wang et al., Acta Materialia 132:598-610, 2017, https://doi.org/10.1016/j.actamat.2017.05.015']
      N_sl: [3, 3, 0, 12]
      dot_gamma_0_sl: [0.001, 0.001, 0.0, 0.001]
      n_sl: [20, 20, 1.0, 20]
      a_sl: [2.0, 2.0, 1.0, 2.0]
      xi_0_sl: [349000000.0, 150000000.0, 0.0, 1107000000.0]
      xi_inf_sl: [568000000.0, 1500000000.0, 0.0, 3420000000.0]
      h_0_sl-sl: [200000000.0, 200000000.0, 0.0, 200000000.0]
      h_sl-sl: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
```

at the last increment of this job (67514), the "u" is 8.3e-6. Did this index mean stain or displacement? But I this what ever is it, maybe this value is too low for the crystal rotation.

Thanks for your assistant!!!
