### DISCUSSION TITLE
Material.yaml and Post-Processing of Dislotwin model

### DISCUSSION THREAD

**Discussion by section10010** [damask-multiphysics/DAMASK#6] [Q&A] [answered]
Dear DAMASK Developer,

I am a beginner of DAMASK, and interested in the dislotwin model. I referred to the "dislotwin_TWIP-TRIP.yaml" file format in the material.config and attempted to modify some parameters. However, I observed that the results for twin volume fraction were very small (around 1e-10 for f_tw in the HDF5 file). I am uncertain whether the issue lies in my input parameters or the post-processing steps. I would appreciate your advice on this matter.

Attached are my input files and the corresponding results.

```
version: alpha8
model size: [1.0e-3, 1.0e-3, 1.0e-3]
cells: [20, 20, 20]
grains: 300
```

material.yaml:
```yaml
phase:
  FCC:
    lattice: cF
    mechanical:
      output: [F, P, F_e, F_p, L_pm, O]
      elastic: {type: Hooke, C_11: 175e+9, C_12: 115e+9, C_44: 135e+9}
      plastic:
        type: dislotwin
        N_sl: [12]
        N_tw: [12]
        b_sl: [2.56e-10]
        b_tw: [1.47e-10]
        Q_sl: [3.5e-19]
        Q_cl: 3.0e-19
        p_sl: [1.0]
        q_sl: [1.15]
        B: [0.001]
        p_tw: [8.0]
        i_sl: [30.0]
        i_tw: 10.0
        L_tw: 1.47e-07
        t_tw: [5.0e-08]
        x_c: 1.0e-09
        V_cs: 1.67e-29
        rho_mob_0: [1.0e+12]
        rho_dip_0: [0]
        v_0: [0.0001]
        tau_0: [3.5e+8]
        gamma_char_tw: [0.35355] #sqrt(2)/4
        D: 5.0e-5
        D_a: 2
        T_ref: 298
        Gamma_sf: 0.01
        h_sl-sl: [0.122, 0.122, 0.625, 0.07, 0.137, 0.137, 0.122]
        h_tw-tw: [0.0, 1]
        h_sl-tw: [0.0, 1, 1]
        output: [rho_mob, rho_dip, gamma_sl, Lambda_sl, tau_pass, f_tw, Lambda_tw]
```

post-processing.ipynb:
```python
import damask
import numpy as np
import matplotlib.pyplot as plt

path = 'Polycystal_300_20x20x20_tensionX_mater_numerics.hdf5' 
res = damask.Result(path)
res.add_stress_Cauchy()
res.add_strain()
res.add_equivalent_Mises('sigma')
res.add_equivalent_Mises('epsilon_V^0.0(F)')
f_tw_data = []
strain_vM_data = []

for i in res.get('f_tw').values():
    temp = np.sum(i,axis=1)
    f_tw_data.append(np.average(temp)*100)
for i in res.get('epsilon_V^0.0(F)_vM').values():
    strain_vM_data.append(np.average(i)*100)

plt.plot(strain_vM_data,f_tw_data)
```

Thank you in advance for your assistance.

Best regards,
Yuxin Liu
